<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>restest</AssemblyName>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
<ItemGroup>
    <Compile Remove="dcheck.cs" />
    <Compile Remove="dcheck2.cs" />
    <Compile Remove="rcheck.cs" />
    <Compile Remove="qcheck.cs" />
    <Compile Remove="nbfixctor.cs" />
    <Compile Remove="nbfixctor2.cs" />
    <Compile Remove="nagstrip.cs" />
    <Compile Remove="nagstrip2.cs" />
    <Compile Remove="nagstrip3.cs" />
    <Compile Remove="nagstrip4.cs" />
    <Compile Remove="nagstrip5.cs" />
    <Compile Remove="roundtrip.cs" />
    <Compile Remove="roundtrip2.cs" />
    <Compile Remove="jittest.cs" />
  </ItemGroup>
</Project>